"""Add payment_method column to Payment model

Revision ID: 0c96fcc2e420
Revises: 4123fab1f729
Create Date: 2025-04-08 18:29:19.571027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c96fcc2e420'
down_revision = '4123fab1f729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_method', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'payment_method')
    # ### end Alembic commands ###
