"""Ensure auto-increment for Payment.id

Revision ID: 12b3d90ca1bd
Revises: b32b19a42a6a
Create Date: 2025-04-02 15:59:30.279265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b3d90ca1bd'
down_revision = 'b32b19a42a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
