"""Applied database changes

Revision ID: 1bcb96452efc
Revises: c23fd0fcd6d6
Create Date: 2025-03-29 22:47:03.201916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcb96452efc'
down_revision = 'c23fd0fcd6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
