"""Add last_harvest_date, last_payment_date, and field_officer to Farmer model

Revision ID: 2ffdb52b3fcf
Revises: 8600662b222e
Create Date: 2025-04-01 23:13:55.164903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffdb52b3fcf'
down_revision = '8600662b222e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer', sa.Column('last_harvest_date', sa.DateTime(), nullable=True))
    op.add_column('farmer', sa.Column('last_payment_date', sa.DateTime(), nullable=True))
    op.add_column('farmer', sa.Column('field_officer', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmer', 'field_officer')
    op.drop_column('farmer', 'last_payment_date')
    op.drop_column('farmer', 'last_harvest_date')
    # ### end Alembic commands ###
