"""Update Update model to autoincrement id

Revision ID: 38c0e20d8edc
Revises: 1bcb96452efc
Create Date: 2025-03-30 20:22:20.785814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c0e20d8edc'
down_revision = '1bcb96452efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
