"""Ensure auto-increment for Payment.id

Revision ID: 41bbec412e2f
Revises: 9aa4c7006f72
Create Date: 2025-04-02 15:15:58.936884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bbec412e2f'
down_revision = '9aa4c7006f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
