"""Enable autoincrement for Harvest.id

Revision ID: 576ce58b26bb
Revises: 7d0bb64468a2
Create Date: 2025-03-31 17:21:11.590991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '576ce58b26bb'
down_revision = '7d0bb64468a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('harvest', 'date_recorded',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('harvest', 'date_recorded',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
