"""Added Update model

Revision ID: 7d0bb64468a2
Revises: a2484ba9238d
Create Date: 2025-03-30 20:50:10.573921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0bb64468a2'
down_revision = 'a2484ba9238d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
