"""Enable autoincrement for Payment.id

Revision ID: 7e3e557ab9b0
Revises: 576ce58b26bb
Create Date: 2025-03-31 19:49:38.810536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3e557ab9b0'
down_revision = '576ce58b26bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
