"""Ensure auto-increment for Payment.id

Revision ID: 9aa4c7006f72
Revises: 2ffdb52b3fcf
Create Date: 2025-04-02 15:11:02.687569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa4c7006f72'
down_revision = '2ffdb52b3fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
