"""Add explicit sequence to Update model

Revision ID: a2484ba9238d
Revises: 38c0e20d8edc
Create Date: 2025-03-30 20:28:48.241134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2484ba9238d'
down_revision = '38c0e20d8edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
