"""Ensure auto-increment for Payment.id

Revision ID: b32b19a42a6a
Revises: 41bbec412e2f
Create Date: 2025-04-02 15:29:27.026440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32b19a42a6a'
down_revision = '41bbec412e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
