"""Set payment.id to autoincrement

Revision ID: bc768e129be2
Revises: 0c96fcc2e420
Create Date: 2025-04-08 18:34:41.207367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc768e129be2'
down_revision = '0c96fcc2e420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
