"""Fix user table id autoincrement

Revision ID: c23fd0fcd6d6
Revises: ede67c4221ef
Create Date: 2025-03-29 21:19:28.710969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23fd0fcd6d6'
down_revision = 'ede67c4221ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
