"""empty message

Revision ID: d429ddb92ed5
Revises: 12b3d90ca1bd
Create Date: 2025-04-04 14:50:38.727358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd429ddb92ed5'
down_revision = '12b3d90ca1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
