"""Initial migration

Revision ID: f396519008f4
Revises: b25be1376a23
Create Date: 2025-03-29 19:15:10.267723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f396519008f4'
down_revision = 'b25be1376a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
